### ISSUE TITLE
add ability to display score brackets by judging group at state

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#832] opened 2020-03-06 20:20 UTC
This is a Jeannie note, so I think it has to do with showing the scores on the scoreboard by judging group (lakes, woods, prarie, marshes, rivers, snow) not tournament group ("state").

**Comment by jpschewe** [comment] 2020-03-07 00:37
Duplicate of #820

**Closed by jpschewe** 2020-03-07 00:37 UTC
