### ISSUE TITLE
Report winners of Tournament

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#918] opened 2021-03-11 20:10 UTC
I was able to enter the winners of tournament but received error when I trie to run the report.  I can live without this for State as I can publish the actual Award script to the website but I would like this for next season

Bug report saved to '/home/jpschewe/demo/fll-sw-linux-15.9.0/web/WEB-INF/bug_2021-03-11_14-061090001997515266096.zip', please notify the computer person in charge to look for bug report files.

**Comment by jpschewe** [comment] 2021-03-12 01:32
This is a duplicate of #911

**Closed by jpschewe** 2021-03-12 01:32 UTC
