### ISSUE TITLE
Software categories need to match schedule/awards script

### ISSUE THREAD

**Issue by eengstrom** [jpschewe/fll-sw#829] opened 2020-03-06 20:19 UTC
Especially at state, the category names in the software often don't match those published in the schedule flyer or the awards script or the spreadsheet for deliberation.  This is VERY confusing.

Jon mentioned that he has a partial implementation of this via the challenge descriptor, but that needs to be part of the pre-state (or other tournament) validation.

As noted at State in 2020
| Schedule                        | Software           |
|:--------------------------------|:-------------------|
| Teamwork                        | Core Values        |
| Project - Research              | Innovation Project |
| Project - Innovative Solution   | (n/a - subjective) |
| Project - Creative Presentation | (n/a - subjective) |
| Robot - Mechanical Design       | Robot Design       |
| Robot - Strategy & Innovation   | (n/a - subjective) |
| Robot - Programming             | Programming        |
| Champions Award                 | Championship       |

**Comment by jpschewe** [comment] 2020-03-07 00:36
I believe this is a duplicate of #810. At least that is how I see this being resolved.

**Closed by jpschewe** 2020-03-07 00:36 UTC
