### ISSUE TITLE
Bug report 7/29 second download attempt

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#744] opened 2019-07-29 20:10 UTC
Downloaded from within build distribution folder, extracted and ran exe from extracted folder

![image](https://user-images.githubusercontent.com/45802417/62078640-ad68e900-b212-11e9-9fbb-3fdd3bb45220.png)
[fll-sw_2019-07-29_15-03-14.1.log](https://github.com/jpschewe/fll-sw/files/3444120/fll-sw_2019-07-29_15-03-14.1.log)

![image](https://user-images.githubusercontent.com/45802417/62078580-8a3e3980-b212-11e9-96a2-75b46a35aa9b.png)

**Comment by jpschewe** [comment] 2019-07-29 21:03
Duplicate of #743.

**Closed** 2019-07-29 21:03 UTC
