### ISSUE TITLE
Suggestion from Judges using software - regarding Comment fields

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#895] opened 2021-02-10 17:06 UTC
Scoring Software -I can't see what comments I have made on the various lines without clicking on every single comment button.  Even just being able to see that there is a comment would be a huge improvement.  Especially since I have to go back to add more comments after the judging and so I can't tell what/where I already have commented.

**Comment by jpschewe** [comment] 2021-02-10 17:18
Duplicate of #892.

**Closed by jpschewe** 2021-02-10 17:18 UTC
