### ISSUE TITLE
Generate RUbric PDF

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#894] opened 2021-02-09 20:31 UTC
Bug report saved to '/home/jpschewe/tournament/fll-sw-linux-15.6.0/web/WEB-INF/bug_2021-02-09_14-2137506568777012270.zip', please notify the computer person in charge to look for bug report files.

I am still getting the error.  Closed the fll tourney software and tried to re-run and received the above bug report.  This report is on Tournament1.  I can generate tournament 2 just fine (though there are no current score in rubrics)

**Comment by jpschewe** [comment] 2021-02-10 14:03
Duplicate of #893

**Closed by jpschewe** 2021-02-10 14:03 UTC
