### ISSUE TITLE
Bug Report - Generate Scores Report

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#889] opened 2021-02-03 19:28 UTC
I entered more scores so every team and Judging Group had at least 2 scores.  I received message that Scores were generated but when I try to print report I get this bug report
Bug report saved to '/home/jpschewe/demo/fll-sw-linux-15.5.0/web/WEB-INF/bug_2021-02-03_13-2315569478862669468845.zip', please notify the computer person in charge to look for bug report files.

Here is the image of scores entered
![image](https://user-images.githubusercontent.com/45802417/106797994-faf1bd80-6622-11eb-98fe-44fa98d8d23c.png)

I then updated so all had at least 3 scores and got a different bug report
![image](https://user-images.githubusercontent.com/45802417/106798478-a3a01d00-6623-11eb-9729-ca5ba3986faf.png)
Bug report saved to '/home/jpschewe/demo/fll-sw-linux-15.5.0/web/WEB-INF/bug_2021-02-03_13-285964845428612017630.zip', please notify the computer person in charge to look for bug report files.

**Comment by jeanniebadger** [comment] 2021-02-03 19:40
I opened 15.5 on my computer and reloaded teams. 

I entered one score for one judging group.  Report ran without Bug Report.
![image](https://user-images.githubusercontent.com/45802417/106799887-663c8f00-6625-11eb-810d-dc3da0f646cf.png)

![image](https://user-images.githubusercontent.com/45802417/106799773-41481c00-6625-11eb-9fcc-dc184334650d.png)

**Comment by jeanniebadger** [comment] 2021-02-03 19:42
Sorry!  I accidentally hit close issue.  Maybe this isn't an issue.  Wondering if I should test one judge in the Live site?

**Comment by jeanniebadger** [comment] 2021-02-03 19:49
THoughts - I know I had at least one judge testing the demo site but I don't see his name entered anywhere "Seph".  Could he hae somehow deleted and that caused the "Null"?

I did run a quick report on the Live site with no judges entered and the reports ran fine and showed performance scores that have been entered.  Which is what I would expect to see.

**Comment by jpschewe** [comment] 2021-02-04 00:28
@jeanniebadger  this appears to be a duplicate of #888. I tested generating the final computed scores with the database in each of the bug reports that you referenced and cannot reproduce the problem with the code that fixes #888.

**Closed by jpschewe** 2021-02-04 00:28 UTC
